apiVersion: apps/v1
kind: Deployment
metadata:
  name: doom
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doom
  template:
    metadata:
      labels:
        app: doom
    spec:
      containers:
      - name: doom
        image: nimpo/iot-doom:v2
        env:
        - name: VNC_PW
          value: "password"
        ports:
        - containerPort: 6901
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 512Mi
